up1:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  right_gripper_controller:
    type: position_controllers/GripperActionController
    joint: right_finger_joint

  right_gripper_fake_controller:
    type: position_controllers/GripperActionController
    joint: right_finger_joint_fake

  right_arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
       - right_armroot_to_armlink1
       - right_armlink1_to_armlink2
       - right_armlink2_to_armlink3
       - right_armlink3_to_armlink4
       - right_armlink4_to_gripper
    constraints:
        # goal_time: 0
        stopped_velocity_tolerance: 0.05
        # right_armroot_to_armlink1: {trajectory: 0.1, goal: 0.1}
        # right_armlink1_to_armlink2: {trajectory: 0.1, goal: 0.1}
        # right_armlink2_to_armlink3: {trajectory: 0.1, goal: 0.1}
        # right_armlink3_to_armlink4: {trajectory: 0.1, goal: 0.1}
        # right_armlink4_to_gripper: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10

  right_jt_cart_controller:
    type: robot_mechanism_controllers/JTCartesianController
    root_name: armroot
    tip_name: right_finger1
    k_posture: 25.0
    jacobian_inverse_damping: 0.01
    pose_command_filter: 0.01
    cart_gains:
      trans:
        p: 800.0
        d: 15.0
      rot:
        p: 80.0
        d: 1.2
    joint_feedforward:
      right_armroot_to_armlink1: 3.33
      right_armlink1_to_armlink2: 1.16
      right_armlink2_to_armlink3: 0.1
      right_armlink3_to_armlink4: 0.25
      right_armlink4_to_gripper: 0.133
    joint_max_effort:
      right_armroot_to_armlink1: 11.88
      right_armlink1_to_armlink2: 11.64
      right_armlink2_to_armlink3: 6.143
      right_armlink3_to_armlink4: 6.804
      right_armlink4_to_gripper: 8.376
    vel_saturation_trans: 2.0
    vel_saturation_rot: 4.0
